version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - echo "No dependencies"
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r lambda_function.zip lambda_function.py
      - ls
      - echo "Seen the contents"

  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp lambda_function.zip s3://door-dash-project-code-19174/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name DoorDash-19174 --s3-bucket door-dash-project-code-19174 --s3-key lambda_function.zip
      - echo "Deployment complete!!"
